export const EXTENSION_ID = "opencodeGui"

export const VIEW_CONTAINER_ID = "opencodeGui"
export const VIEW_ID = "opencodeGui.view"

export const COMMAND_OPEN = "opencodeGui.open"
export const COMMAND_NEW_SESSION = "opencodeGui.newSession"
export const COMMAND_REFRESH = "opencodeGui.refresh"
export const COMMAND_COPY_FILE_REFERENCE = "opencodeGui.copyFileReference"
export const COMMAND_SEND_CONTEXT = "opencodeGui.sendContextToSession"
export const COMMAND_ABORT_SESSION = "opencodeGui.abortActiveSession"
export const COMMAND_OPEN_REFERENCE = "opencodeGui.openReferenceInEditor"
export const COMMAND_OPEN_PANEL = "opencodeGui.openPanel"
export const COMMAND_SWITCH_SESSION = "opencodeGui.switchSession"
export const COMMAND_REVIEW_PERMISSIONS = "opencodeGui.reviewPermissions"
export const COMMAND_SHOW_SESSION_TODO = "opencodeGui.showSessionTodo"
export const COMMAND_SHOW_SESSION_DIFF = "opencodeGui.showSessionDiff"
export const COMMAND_RUN_SESSION_COMMAND = "opencodeGui.runSessionCommand"
export const COMMAND_RUN_SESSION_SHELL = "opencodeGui.runSessionShell"
export const COMMAND_RENAME_SESSION = "opencodeGui.renameSession"
export const COMMAND_DELETE_SESSION = "opencodeGui.deleteSession"
export const COMMAND_FORK_SESSION = "opencodeGui.forkSession"
export const COMMAND_SHARE_SESSION = "opencodeGui.shareSession"
export const COMMAND_UNSHARE_SESSION = "opencodeGui.unshareSession"
export const COMMAND_COMPACT_SESSION = "opencodeGui.compactSession"
export const COMMAND_SESSION_ACTIONS = "opencodeGui.sessionActions"
export const COMMAND_ATTACH_FILE = "opencodeGui.attachFileContext"
export const COMMAND_ATTACH_EXPLORER_FILE = "opencodeGui.attachExplorerFileContext"
export const COMMAND_ATTACH_SYMBOL = "opencodeGui.attachSymbolContext"
export const COMMAND_ATTACH_GIT_DIFF = "opencodeGui.attachGitDiffContext"

export const CONFIG_NS = "opencodeGui"
